'use strict';
const $=id=>document.getElementById(id), hospital=location.pathname==='/hospital';
let current=null,selected='',pending=null,busy=false,epoch=0,lastSync=null;
const labels={blood_pressure:'Blood pressure',heart_rate:'Heart rate',temperature:'Temperature',oxygen_saturation:'Oxygen saturation'};
const fields=Object.keys(labels);
if(hospital){$('title').textContent='Hospital handoff dashboard';document.querySelectorAll('.editor').forEach(e=>e.hidden=true);}
// Authoritative symptom options are loaded from the server.
function notice(s){$('notice').textContent=s;}
function id(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);}
async function api(path,body){const headers={};const token=sessionStorage.getItem('midai_api_token');if(token)headers.Authorization='Bearer '+token;if(body!==undefined)headers['Content-Type']='application/json';const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch(path,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:JSON.stringify(body),signal:controller.signal,cache:'no-store'});const data=await r.json();if(!r.ok){const e=new Error(data.message||data.error||'Request failed');e.status=r.status;throw e;}return data;}finally{clearTimeout(timer);}}
function connection(ok,error){if(ok)lastSync=new Date().toLocaleTimeString();$('connection').textContent=(ok?'Connected':'Connection problem: '+error)+' · Last refresh: '+(lastSync||'never');}
function cell(text){const e=document.createElement('td');e.textContent=text;return e;}
function value(m){if(!m)return 'Not measured';if(m.status!=='recorded')return {unknown:'Unknown',not_measured:'Not measured',needs_confirmation:'Needs confirmation'}[m.status]||m.status;return m.value+(m.value_secondary!==null?'/'+m.value_secondary:'')+' '+m.unit;}
function controls(){document.querySelectorAll('.write button,button.write').forEach(e=>e.disabled=busy||!!pending||!current||current.status==='finished');$('intake').querySelector('button').disabled=busy||!!pending;$('retry').hidden=!pending;$('retry').disabled=busy;$('closed').hidden=!current||current.status!=='finished';}
function render(s){current=s;selected=s.case_id;$('cases').value=selected;$('caseTitle').textContent='Case '+s.case_id.slice(0,8);$('meta').textContent=s.case_id+' · Version '+s.version+' · Updated '+s.updated_at;$('status').textContent=s.status;$('protocol').textContent=s.protocol.matched_protocol||'No supported match';$('source').textContent=s.data.deteriorating?'Flag raised — review required':'No source flag';$('confirmation').textContent=s.confirmation.value;$('details').textContent='Symptoms: '+(s.data.symptoms||[]).join(', ')+' · Breathing: '+(s.data.is_breathing||'unknown');$('sbar').textContent=s.sbar_report;
$('vitals').replaceChildren();for(const field of fields){const all=(s.structured_vitals||[]).filter(m=>m.field===field);const m=all[all.length-1];const card=document.createElement('div');card.className='card';const label=document.createElement('small'),v=document.createElement('strong'),detail=document.createElement('p');label.textContent=labels[field];v.textContent=value(m);detail.textContent=m?'Raw: '+JSON.stringify(m.raw_value)+' · '+(m.source_time||'Unknown source time')+' · '+m.time_status:'No saved check';card.append(label,v,detail);$('vitals').append(card);}
$('timeline').replaceChildren();s.vitals.forEach((v,i)=>{const row=document.createElement('tr');row.append(cell(v.timestamp||'Unknown'));for(const f of fields)row.append(cell(value((s.structured_vitals||[]).find(m=>m.sequence===i&&m.field===f))));row.append(cell(v.status_change||'Unknown'));$('timeline').append(row);});
$('history').replaceChildren();for(const e of s.events.filter(e=>['protocol','audit','intervention'].includes(e.kind)).slice(-30).reverse()){const p=document.createElement('div');p.className='event';let message=e.kind==='protocol'?`${e.payload.previous||'None'} → ${e.payload.matched_protocol||'None'}`:e.kind==='intervention'?`${e.payload.action} · Response: ${e.payload.response||'Unknown'}`:`${e.payload.operation} · ${e.payload.reason}`;p.textContent=e.recorded_at+' · '+message;if(e.kind==='audit'){const d=document.createElement('details'),h=document.createElement('summary'),pre=document.createElement('pre');h.textContent='View before / after';pre.textContent=JSON.stringify({before:e.payload.before,after:e.payload.after},null,2);d.append(h,pre);p.append(d);}$('history').append(p);}controls();}
async function refresh(){if(busy)return;const version=epoch,chosen=selected;try{const list=await api('/cases');if(epoch!==version)return;$('cases').replaceChildren();const empty=document.createElement('option');empty.value='';empty.textContent='Select a saved case';$('cases').append(empty);for(const c of list.cases){const o=document.createElement('option');o.value=c.case_id;o.textContent=c.case_id.slice(0,8)+' · '+new Date(c.created_at).toLocaleString();$('cases').append(o);}$('cases').value=chosen;if(chosen){const s=await api('/cases/'+encodeURIComponent(chosen));if(epoch===version&&!busy)render(s);}connection(true);}catch(e){connection(false,e.message);}}
async function load(){if(pending)throw new Error('Resolve the unconfirmed save before changing cases.');const chosen=$('cases').value;if(!chosen)throw new Error('Choose a case first.');selected=chosen;epoch++;render(await api('/cases/'+encodeURIComponent(chosen)));notice('Case loaded. Updates refresh automatically.');}
async function retry(){if(!pending)return;try{const s=await api(pending.path,pending.body);pending=null;epoch++;render(s);notice('Saved successfully.');}catch(e){if(e.status&&e.status<500)pending=null;notice(e.status===409?'Conflict: reload the case, review your changes and submit again.':e.message+' — if the save is unconfirmed, retry the same request.');throw e;}finally{controls();}}
async function save(path,body){if(pending)throw new Error('Retry the previous unconfirmed save first.');pending={path,body};await retry();}
async function change(op,payload,reason,version){if(!current||current.status==='finished')throw new Error('Load an active case first.');return save('/cases/'+encodeURIComponent(current.case_id)+'/'+op,{payload,reason,expected_version:version??current.version,request_id:id()});}
function action(element,fn,event='click'){element.addEventListener(event,async e=>{e.preventDefault();if(busy)return;busy=true;epoch++;controls();try{await fn();}catch(err){notice(err.status===409?'Conflict: reload and review before submitting again.':err.message);}finally{busy=false;controls();}});}
function form(name,fn){const f=$(name);f.addEventListener('focusin',()=>{if(!f.dataset.version&&current){f.dataset.version=current.version;f.dataset.case=current.case_id;}});action(f,async()=>{if(f.dataset.case&&f.dataset.case!==selected)throw new Error('This form belongs to the previous case. Clear it and enter the new case data.');await fn(Object.fromEntries(new FormData(f)),f.dataset.version?Number(f.dataset.version):undefined);f.reset();delete f.dataset.version;delete f.dataset.case;},'submit');}
action($('connect'),async()=>{const t=$('token').value.trim();if(t)sessionStorage.setItem('midai_api_token',t);else sessionStorage.removeItem('midai_api_token');$('token').value='';notice('Connection settings applied.');});action($('load'),load);$('refresh').onclick=refresh;action($('retry'),retry);
$('cases').addEventListener('change',()=>{document.querySelectorAll('.write').forEach(f=>{if(f.tagName==='FORM'){f.reset();delete f.dataset.version;delete f.dataset.case;}});});
form('intake',async data=>{data.symptoms=Array.from($('symptoms').selectedOptions).map(o=>o.value);for(const k of Object.keys(data))if(data[k]==='')delete data[k];await save('/cases',{data,request_id:id()});});
form('observation',(data,v)=>{for(const k of Object.keys(data))if(data[k].trim()==='')delete data[k];if(!Object.keys(data).length)throw new Error('Enter at least one reading or reported change.');return change('observations',data,'Responder-entered check',v);});
form('correction',(data,v)=>change('corrections',{[data.field]:data.field==='symptoms'?data.value.split(',').map(x=>x.trim()).filter(Boolean):data.value},data.reason,v));
form('confirmForm',(data,v)=>change('confirmation',data,'Responder confirmation',v));form('intervention',(data,v)=>change('interventions',data,'Reported performed intervention',v));
action($('finish'),async()=>{if(confirm('Finish this handoff? Further updates will be blocked. Stop the terminal voice collector first.'))await change('finish',{},'Handoff complete');});
$('download').onclick=()=>{if(!current)return notice('Load a case first.');const url=URL.createObjectURL(new Blob([current.sbar_report],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='SBAR-'+current.case_id+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
action($('cases'),load,'change');
api('/ui-config').then(config=>{for(const s of config.symptoms){const o=document.createElement('option');o.value=s;o.textContent=s;$('symptoms').append(o);}}).catch(e=>notice('Could not load symptom choices: '+e.message));controls();refresh();setInterval(refresh,4000);
